platform :ios, '12.0'
use_frameworks!

target 'LoginKitSample' do
  pod 'SnapSDK', '2.4.0', :subspecs => ['SCSDKLoginKit']
end

target 'LoginKitSampleTests' do

end

target 'LoginKitSampleUITests' do

end
